### ISSUE TITLE
ImportError: No module named Leap

### ISSUE THREAD

**Issue by luis84** [openleap/PyLeapMouse#16]
Hi there,

Running this on LM 14 (Debian/Ubuntu).  I have copied the files as instructed and when I launch PyLeapMouse with python I get this:

Traceback (most recent call last):
  File "PyLeapMouse.py", line 4, in <module>
    from leap import Leap, Mouse
  File "/home/zero/Downloads/PyLeapMouse-master/leap.py", line 6, in <module>
    import Linux.Leap as Leap
ImportError: No module named Leap

I have the SDK properly installed and can run Visualizer and other non python Leap apps.

When I run located Leap.so I cannot even find a Leap.so file on my system, there is libleap.so but no Leap.so

**Comment by pouyaAB** [comment]
You need to download the SDK from this [link](https://developer.leapmotion.com/sdk/v2). In this you can find a folder named LeapSDK. Put in the $HOME and do this:

export PYTHONPATH=$PYTHONPATH:$HOME/LeapSDK/lib:$HOME/LeapSDK/lib/x64

**Comment by renexdev** [comment]
Thanks @pouyaAB  works for me too!
