### ISSUE TITLE
Missing parentheses in call to 'print' .Did you mean print(..)? and ..

### ISSUE THREAD

**Issue by swordfishvirus** [openleap/PyLeapMouse#39]
PS C:\Users\Gigg\Desktop\PyLeapMouse-master> python PyleapMouse.py
  File "C:\Users\Gigg\Desktop\PyLeapMouse-master\PyleapMouse.py", line 10
    print "----------------------------------PyLeapMouse----------------------------------"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
PS C:\Users\Gigg\Desktop\PyLeapMouse-master> python PyleapMouse.py
Traceback (most recent call last):
  File "C:\Users\Gigg\Desktop\PyLeapMouse-master\PyleapMouse.py", line 4, in <module>
    from leap import Leap, Mouse
  File "C:\Users\Gigg\Desktop\PyLeapMouse-master\leap.py", line 11, in <module>
    import Windows.Leap as Leap
ModuleNotFoundError: No module named 'Windows.Leap'

**Comment by wyager** [comment]
Python2 vs python3 syntax. If you manage to get this working for python3, I'd welcome a PR to update it.
